# Generated by Django 6.0.3 on 2026-03-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leverancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('contactpersoon', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('omschrijving', models.TextField(blank=True)),
                ('usps', models.TextField(blank=True, help_text="USP's, één per regel")),
                ('afbeelding', models.ImageField(blank=True, null=True, upload_to='product_afbeeldingen/')),
                ('inkoopprijs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('winstmarge_procent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prijs_laatst_gewijzigd', models.DateField(blank=True, null=True)),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('leverancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producten', to='pricelist.leverancier')),
            ],
        ),
        migrations.CreateModel(
            name='PrijsHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oude_inkoopprijs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nieuwe_inkoopprijs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wijzigingsdatum', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prijshistorie', to='pricelist.product')),
            ],
        ),
        migrations.CreateModel(
            name='Combinatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('omschrijving', models.TextField(blank=True)),
                ('combinatie_verkoopprijs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producten', models.ManyToManyField(blank=True, related_name='combinaties', to='pricelist.product')),
            ],
        ),
    ]
