# Generated by Django 6.0.3 on 2026-03-21 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_frontend_roles_and_profiles(apps, schema_editor):
    FrontendRole = apps.get_model("pricelist", "FrontendRole")
    UserFrontendProfile = apps.get_model("pricelist", "UserFrontendProfile")
    User = apps.get_model("auth", "User")

    admin_r = FrontendRole.objects.create(
        name="Administrator",
        slug="administrator",
        sort_order=0,
        description="Full frontend access, including permanent catalog delete.",
        access_price_list=True,
        access_catalog=True,
        catalog_change=True,
        catalog_soft_delete=True,
        catalog_trash=True,
        catalog_purge=True,
        access_proposals=True,
        access_invoicing=True,
        access_orders=True,
        access_contacts=True,
        contacts_write=True,
    )
    sales_r = FrontendRole.objects.create(
        name="Sales",
        slug="sales",
        sort_order=10,
        description="Quotes, invoices, orders, and CRM. No catalog management.",
        access_price_list=True,
        access_catalog=False,
        catalog_change=False,
        catalog_soft_delete=False,
        catalog_trash=False,
        catalog_purge=False,
        access_proposals=True,
        access_invoicing=True,
        access_orders=True,
        access_contacts=True,
        contacts_write=True,
    )
    cat_r = FrontendRole.objects.create(
        name="Catalog manager",
        slug="catalog_manager",
        sort_order=20,
        description="Price list and catalog only; can soft-delete and restore, not purge.",
        access_price_list=True,
        access_catalog=True,
        catalog_change=True,
        catalog_soft_delete=True,
        catalog_trash=True,
        catalog_purge=False,
        access_proposals=False,
        access_invoicing=False,
        access_orders=False,
        access_contacts=False,
        contacts_write=False,
    )
    proc_r = FrontendRole.objects.create(
        name="Procurement",
        slug="procurement",
        sort_order=30,
        description="Price list, purchase orders, and read-only contacts.",
        access_price_list=True,
        access_catalog=False,
        catalog_change=False,
        catalog_soft_delete=False,
        catalog_trash=False,
        catalog_purge=False,
        access_proposals=False,
        access_invoicing=False,
        access_orders=True,
        access_contacts=True,
        contacts_write=False,
    )

    for u in User.objects.all():
        if getattr(u, "is_superuser", False) or getattr(u, "is_staff", False):
            role = admin_r
        else:
            role = sales_r
        UserFrontendProfile.objects.get_or_create(user=u, defaults={"role": role})


def unseed_frontend_roles(apps, schema_editor):
    UserFrontendProfile = apps.get_model("pricelist", "UserFrontendProfile")
    FrontendRole = apps.get_model("pricelist", "FrontendRole")
    UserFrontendProfile.objects.all().delete()
    FrontendRole.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Stable key for imports and seeds (lowercase, no spaces).', max_length=64, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
                ('access_price_list', models.BooleanField(default=True, help_text='Browse price list and product detail pages.', verbose_name='Price list')),
                ('access_catalog', models.BooleanField(default=False, help_text='See the Products (catalog management) menu and catalog URLs.', verbose_name='Catalog section')),
                ('catalog_change', models.BooleanField(default=False, help_text='Create and edit products, combinations, and use the image library (including deletes there).', verbose_name='Catalog: add and edit')),
                ('catalog_soft_delete', models.BooleanField(default=False, help_text='Soft-delete products or combinations (recoverable).', verbose_name='Catalog: remove to trash')),
                ('catalog_trash', models.BooleanField(default=False, help_text='Open trash views and restore soft-deleted catalog rows.', verbose_name='Catalog: trash and restore')),
                ('catalog_purge', models.BooleanField(default=False, help_text='Permanently delete soft-deleted products or combinations from trash.', verbose_name='Catalog: permanent delete')),
                ('access_proposals', models.BooleanField(default=False, help_text='New proposal, saved calculations, and proposal tools.', verbose_name='Proposals')),
                ('access_invoicing', models.BooleanField(default=False, help_text='Invoices list, detail, and status changes.', verbose_name='Invoicing')),
                ('access_orders', models.BooleanField(default=False, help_text='Purchase orders list and detail (tracking what to order).', verbose_name='Orders')),
                ('access_contacts', models.BooleanField(default=False, help_text='Contacts menu and organization/person pages.', verbose_name='Contacts (CRM)')),
                ('contacts_write', models.BooleanField(default=False, help_text='Create or edit organizations, people, departments, memberships, and links.', verbose_name='Contacts: add and edit')),
            ],
            options={
                'verbose_name': 'Frontend role',
                'verbose_name_plural': 'Frontend roles',
                'db_table': 'catalogus_frontendrole',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserFrontendProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='pricelist.frontendrole', verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User frontend access',
                'verbose_name_plural': 'User frontend access',
                'db_table': 'catalogus_userfrontendprofile',
            },
        ),
        migrations.RunPython(seed_frontend_roles_and_profiles, unseed_frontend_roles),
    ]
