# Generated by Django 6.0.3 on 2026-03-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prijs_laatst_gecontroleerd',
            field=models.DateField(blank=True, help_text='Datum waarop de prijs voor het laatst inhoudelijk gecontroleerd is.', null=True),
        ),
    ]
