# Generated by Django 6.0.3 on 2026-03-21 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def forwards_invoice_sent_to_unpaid(apps, schema_editor):
    Invoice = apps.get_model("pricelist", "Invoice")
    Invoice.objects.filter(status="sent").update(status="unpaid")


def backwards_invoice_unpaid_to_sent(apps, schema_editor):
    Invoice = apps.get_model("pricelist", "Invoice")
    Invoice.objects.filter(status="unpaid").update(status="sent")


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_frontend_access_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Optional display number; can be assigned when the invoice is issued.', max_length=64, verbose_name='Invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, help_text='Set when the invoice is marked as issued.', null=True, verbose_name='Issued at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='Draft: internal. Unpaid: issued to the customer. Record payments to track partial or full payment.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Draft: not yet sent to suppliers. Sent: with supplier(s). Paid: customer invoice fully paid (usually automatic). Completed: all delivered. Cancelled.', max_length=32, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for this payment row.', unique=True, verbose_name='UUID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('paid_at', models.DateTimeField(help_text='When the payment was received.', verbose_name='Paid at')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoice_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recorded by')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pricelist.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice payment',
                'verbose_name_plural': 'Invoice payments',
                'db_table': 'catalogus_invoicepayment',
                'ordering': ('-paid_at', '-pk'),
            },
        ),
        migrations.RunPython(forwards_invoice_sent_to_unpaid, backwards_invoice_unpaid_to_sent),
    ]
