# Generated by Django 6.0.3 on 2026-03-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0002_product_prijs_laatst_gecontroleerd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, unique=True)),
                ('volgorde', models.PositiveIntegerField(default=0, help_text='Optioneel: gebruik dit om categorieën te sorteren.')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categorieën',
                'ordering': ('volgorde', 'naam'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producten', to='pricelist.categorie'),
        ),
    ]
