# Generated by Django 6.0.3 on 2026-03-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0003_categorie_product_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallatieFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, unique=True)),
                ('bedrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('omschrijving', models.TextField(blank=True)),
                ('actief', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Installatiefee',
                'verbose_name_plural': "Installatiefee's",
                'ordering': ('naam',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='installatie_fee',
            field=models.ForeignKey(blank=True, help_text='Optionele installatiefee die wordt opgeteld bij de verkoopprijs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producten', to='pricelist.installatiefee'),
        ),
    ]
