# Generated by Django 6.0.3 on 2026-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0004_installatiefee_product_installatie_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, unique=True)),
                ('bedrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('omschrijving', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('installatie', 'Installatie'), ('upgrade', 'Upgrade'), ('overig', 'Overig')], default='overig', max_length=32)),
                ('actief', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Optie',
                'verbose_name_plural': 'Opties',
                'ordering': ('naam',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='installatie_fee',
        ),
        migrations.AddField(
            model_name='product',
            name='opties',
            field=models.ManyToManyField(blank=True, related_name='producten', to='pricelist.optie'),
        ),
        migrations.DeleteModel(
            name='InstallatieFee',
        ),
    ]
