# Generated by Django 6.0.3 on 2026-03-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0005_optie_remove_product_installatie_fee_product_opties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optie',
            name='categorien',
            field=models.ManyToManyField(blank=True, help_text="Leeg = optie voor alle producten. Anders alleen tonen bij producten in één van deze categorieën (bijv. alleen bij kassa's).", related_name='opties', to='pricelist.categorie'),
        ),
        migrations.AlterField(
            model_name='optie',
            name='actief',
            field=models.BooleanField(default=True, help_text='Inactieve opties verschijnen niet meer bij het toevoegen van opties aan nieuwe producten; bestaande koppelingen blijven zichtbaar.'),
        ),
    ]
