# Generated by Django 6.0.3 on 2026-03-13 12:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0006_optie_categorien'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinstProfiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, unique=True)),
                ('opslag_percentage', models.DecimalField(decimal_places=2, help_text='Percentage-opslag op de inkoopprijs (bijv. 30 voor 30%).', max_digits=5)),
                ('opslag_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Vaste opslag in euro's die wordt opgeteld bij de verkoopprijs.", max_digits=10)),
                ('actief', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Winstprofiel',
                'verbose_name_plural': 'Winstprofielen',
                'ordering': ('naam',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bestelnummer_leverancier',
            field=models.CharField(blank=True, help_text='Bestel-/artikelnummer zoals gehanteerd door de leverancier.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='merk',
            field=models.CharField(blank=True, help_text='Bijv. HP, Epson, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, help_text='Bijv. modelnaam of type.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='naam',
            field=models.CharField(help_text='Volledige benaming; optioneel combinatie van merk + type.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='winstmarge_procent',
            field=models.DecimalField(decimal_places=2, help_text='Fallback marge in %, gebruikt als er geen winstprofiel is gekoppeld.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='winstprofiel',
            field=models.ForeignKey(blank=True, help_text='Optioneel centraal winstprofiel. Indien gezet, gaat dit boven de product-specifieke marge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producten', to='pricelist.winstprofiel'),
        ),
    ]
