# Generated by Django 6.0.3 on 2026-03-13 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0007_merk_type_winstprofiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='winstmarge_procent',
        ),
        migrations.AlterField(
            model_name='product',
            name='naam',
            field=models.CharField(blank=True, help_text='Verouderd veld, wordt niet meer gebruikt. Gebruik merk + type.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='winstprofiel',
            field=models.ForeignKey(blank=True, help_text='Verplicht winstprofiel voor dit product (in de admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producten', to='pricelist.winstprofiel'),
        ),
    ]
