# Generated by Django 6.0.3 on 2026-03-22 19:47

from django.db import migrations, models


def _default_contract_calculation_options():
    return {
        "version": 1,
        "hardware_fee_basis": "sales_line_totals",
        "labour_unit_basis": "all_units",
        "include_hardware_fee": True,
        "include_labour": True,
        "override_time_per_product_minutes": None,
        "override_minimum_visit_minutes": None,
        "override_hourly_rate": None,
        "override_hardware_fee_percentage": None,
        "override_visits_per_contract": None,
    }


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0008_proposal_calculation_contract_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractduration',
            name='contract_calculation_defaults',
            field=models.JSONField(default=_default_contract_calculation_options, help_text='How hardware fee and labour are derived for this duration (fee base, labour counting, optional overrides). Filled when you create a duration from a proposal calculation model; editable here for reuse.', verbose_name='Contract calculation defaults'),
        ),
    ]
