# Generated by Django 6.0.3 on 2026-03-13 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0008_remove_product_winstmarge_procent_alter_product_naam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optie',
            name='gerelateerd_product',
            field=models.ForeignKey(blank=True, help_text='Optioneel: koppel deze optie aan een product dat ook los verkocht kan worden (bijv. fanless hub).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_optie', to='pricelist.product'),
        ),
    ]
