# Generated by Django 6.0.3 on 2026-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0009_optie_gerelateerd_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optie',
            name='bedrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optionele vaste prijs voor deze optie. Leeg laten om automatisch de prijs van het gerelateerde product te gebruiken.', max_digits=10, null=True),
        ),
    ]
