# Generated by Django 6.0.3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pricelist", "0009_contract_duration_calc_defaults"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProposalCalculationModel",
        ),
        migrations.RemoveField(
            model_name="contractduration",
            name="contract_calculation_defaults",
        ),
    ]
