# Generated by Django 6.0.3 on 2026-03-13 14:17

import pricelist.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0010_optie_bedrag_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artikelnummer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Technisch artikelnummer (UUID) voor bestandsnamen en koppelingen.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='afbeelding',
            field=models.ImageField(blank=True, null=True, upload_to=pricelist.models.product_afbeelding_upload_to),
        ),
    ]
