# Generated by Django 6.0.3 on 2026-03-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0010_remove_proposal_calculation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractduration',
            name='hardware_fee_basis',
            field=models.CharField(choices=[('sales_line_totals', 'Sum of line totals (sales value)'), ('cost_line_totals', 'Sum of line totals (catalog cost)'), ('margin_sales_only', 'Margin products only — sales value'), ('margin_cost_only', 'Margin products only — catalog cost')], default='sales_line_totals', help_text='Which cart line amounts the hardware fee percentage is applied to.', max_length=32, verbose_name='Hardware fee base'),
        ),
        migrations.AddField(
            model_name='contractduration',
            name='include_hardware_fee_in_contract',
            field=models.BooleanField(default=True, help_text='If unchecked, the contract total excludes the hardware fee for this duration.', verbose_name='Include hardware fee in contract total'),
        ),
        migrations.AddField(
            model_name='contractduration',
            name='include_labour_in_contract',
            field=models.BooleanField(default=True, help_text='If unchecked, the contract total excludes labour for this duration.', verbose_name='Include labour in contract total'),
        ),
        migrations.AddField(
            model_name='contractduration',
            name='labour_unit_basis',
            field=models.CharField(choices=[('all_units', 'Count quantity on every line'), ('margin_products_only', 'Count only margin products (hardware)'), ('exclude_combinations', 'Exclude packages — products only')], default='all_units', help_text='Which lines contribute to the product count for labour time (minutes × products).', max_length=32, verbose_name='Labour / visit count'),
        ),
        migrations.AddField(
            model_name='contractduration',
            name='override_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the value from general settings.', max_digits=10, null=True, verbose_name='Override: hourly rate'),
        ),
        migrations.AddField(
            model_name='contractduration',
            name='override_minimum_visit_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the value from general settings.', max_digits=6, null=True, verbose_name='Override: minimum visit (minutes)'),
        ),
        migrations.AddField(
            model_name='contractduration',
            name='override_time_per_product_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the value from general settings.', max_digits=6, null=True, verbose_name='Override: time per product (minutes)'),
        ),
    ]
