# Generated by Django 6.0.3 on 2026-03-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0011_product_artikelnummer_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgemeneInstellingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuta', models.CharField(default='EUR', help_text='Valutacode of symbool voor weergave, bijv. EUR of €.', max_length=32)),
                ('afronding', models.CharField(default='0.01', help_text='Afrondingssyntax: getal = afronden op dat bedrag (0.01, 0.05, 0.10, 0.50, 1, 5, 10, …). Optie: getal-min (bijv. 1-0.01) = afronden op hele eenheden en dan min bedrag aftrekken (bijv. 10,99).', max_length=64)),
            ],
            options={
                'verbose_name': 'Algemene instelling',
                'verbose_name_plural': 'Algemene instellingen',
            },
        ),
        migrations.AlterField(
            model_name='optie',
            name='categorien',
            field=models.ManyToManyField(blank=True, help_text="Bij welke productcategorieën deze optie kiesbaar is. Leeg = bij alle producten. Bijv. Kassa = alleen zichtbaar wanneer je een product in categorie Kassa bewerkt (zo kun je een randapparaat als optie bij kassa's aanbieden).", related_name='opties', to='pricelist.categorie'),
        ),
        migrations.AlterField(
            model_name='optie',
            name='gerelateerd_product',
            field=models.ForeignKey(blank=True, help_text='Het product waarvan de verkoopprijs wordt getoond (bijv. het los verkoopbare artikel zoals de hub). Niet het product waar de optie bij wordt aangeboden (bijv. de kassa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='als_optie', to='pricelist.product'),
        ),
    ]
