# Generated by Django 6.0.3 on 2026-03-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0012_algemene_instellingen'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='getalnotatie',
            field=models.CharField(choices=[('eu', 'Europa (punt voor duizendtallen, komma voor decimalen: 1.000,00)'), ('us', 'Amerika (komma voor duizendtallen, punt voor decimalen: 1,000.00)')], default='eu', help_text='Scheidingstekens: Europa = 1.000,00 ; Amerika = 1,000.00', max_length=8),
        ),
    ]
