# Generated by Django 6.0.3 on 2026-03-13 17:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0013_getalnotatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='minimale_marge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimale marge voor combinaties in %, bijv. 20 voor 20%. Onder deze waarde verschijnt een waarschuwing in de backend.', max_digits=5),
        ),
    ]
