# Generated by Django 6.0.3 on 2026-03-13 17:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0014_minimale_marge'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinatie',
            name='aanbieding_korting_bedrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vast kortingsbedrag dat van de optelsom van de losse verkoopprijzen wordt afgetrokken.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='combinatie',
            name='aanbieding_korting_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kortingspercentage dat over de optelsom van de losse verkoopprijzen wordt berekend (bijv. 10 = 10%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='combinatie',
            name='aanbieding_type',
            field=models.CharField(choices=[('vast_bedrag', 'Vast bedrag (aanbiedingsprijs)'), ('korting_bedrag', 'Vast kortingsbedrag'), ('korting_percentage', 'Kortingspercentage')], default='vast_bedrag', help_text='Hoe de prijs van de combinatie wordt bepaald.', max_length=32),
        ),
        migrations.AddField(
            model_name='combinatie',
            name='aanbieding_vast_bedrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Aanbiedingsprijs voor de hele combinatie (wordt direct gebruikt als 'voor'-prijs).", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='algemeneinstellingen',
            name='minimale_marge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimale marge in % voor combinaties (bijv. 20 = minimaal 20% marge). Bij 0 wordt er niet gecontroleerd.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='combinatie',
            name='combinatie_verkoopprijs',
            field=models.DecimalField(decimal_places=2, help_text='Historisch veld: uiteindelijke aanbiedingsprijs. Wordt automatisch gevuld op basis van het gekozen type en kortingsvelden.', max_digits=10),
        ),
    ]
