# Generated by Django 6.0.3 on 2026-03-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0016_uuid_en_delete_rechten'),
    ]

    operations = [
        migrations.AddField(
            model_name='optie',
            name='inkoopprijs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optionele inkoopprijs voor deze optie. In combinatie met marge en vaste opslag wordt hieruit de verkoopprijs berekend.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='optie',
            name='marge_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marge in % over de inkoopprijs (bijv. 30 = 30%).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='optie',
            name='opslag_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Vaste opslag in euro's bovenop de inkoop+marge.", max_digits=10, null=True),
        ),
    ]
