# Generated by Django 6.0.3 on 2026-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0017_optie_marge_prijs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kan_worden_gebruikt_als_optie',
            field=models.BooleanField(default=True, help_text="Of dit product gekozen mag worden als 'gerelateerd product' bij opties."),
        ),
        migrations.AddField(
            model_name='product',
            name='toon_in_prijslijst',
            field=models.BooleanField(default=True, help_text='Als dit uit staat, wordt het product niet als los product op de prijslijst getoond (maar kan het wel als optie gebruikt worden).'),
        ),
    ]
