# Generated by Django 6.0.3 on 2026-03-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0018_product_flags_prijslijst_optie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='opties',
        ),
        migrations.DeleteModel(
            name='Optie',
        ),
    ]
