# Generated by Django 6.0.3 on 2026-03-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0019_remove_optie_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kan_worden_gebruikt_als_optie',
        ),
        migrations.RemoveField(
            model_name='product',
            name='toon_in_prijslijst',
        ),
    ]
