# Generated by Django 6.0.3 on 2026-03-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0020_remove_product_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='optie_voor',
            field=models.ManyToManyField(blank=True, help_text='Geef hier aan bij welk product of welke producten dit artikel als optie wordt aangeboden (bijv. Lemur-C Ethernet als optie bij Lemur-C).', related_name='opties', to='pricelist.product', verbose_name='Optie voor product(en)'),
        ),
    ]
