# Generated by Django 6.0.3 on 2026-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0021_product_optie_voor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='toon_in_prijslijst',
            field=models.BooleanField(default=True, help_text='Als uitgeschakeld: dit product verschijnt niet als los artikel op de prijslijst. Als het wel als optie bij een ander product staat, blijft het daar wel zichtbaar.', verbose_name='Toon in prijslijst'),
        ),
    ]
