# Generated by Django 6.0.3 on 2026-03-13 20:49

import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import OperationalError


def copy_optie_voor_to_productoptie(apps, schema_editor):
    """Kopieer bestaande optie_voor M2M-relaties naar ProductOptie (hoofdproduct=to, optie_product=from)."""
    ProductOptie = apps.get_model("pricelist", "ProductOptie")
    # Django M2M to self: table catalogus_product_optie_voor, columns from_product_id, to_product_id
    # "from" = het product waar we optie_voor op zetten (het optie-product), "to" = het hoofdproduct
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute(
                "SELECT from_product_id, to_product_id FROM catalogus_product_optie_voor"
            )
        except OperationalError:
            # Fresh DB / tests: M2M table never existed (field added in same migration path).
            return
        for from_id, to_id in cursor.fetchall():
            ProductOptie.objects.get_or_create(
                hoofdproduct_id=to_id,
                optie_product_id=from_id,
                defaults={"volgorde": 0},
            )


def copy_combinatie_producten_to_items(apps, schema_editor):
    """Maak voor elke (combinatie, product) in de oude producten M2M een CombinatieItem."""
    CombinatieItem = apps.get_model("pricelist", "CombinatieItem")
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute(
                "SELECT combinatie_id, product_id FROM catalogus_combinatie_producten"
            )
        except OperationalError:
            return
        for volgorde, (combi_id, product_id) in enumerate(cursor.fetchall(), start=0):
            CombinatieItem.objects.get_or_create(
                combinatie_id=combi_id,
                product_id=product_id,
                defaults={"volgorde": volgorde},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("pricelist", "0022_product_toon_in_prijslijst"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombinatieItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("volgorde", models.PositiveIntegerField(default=0, verbose_name="Volgorde")),
                ("combinatie", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="pricelist.combinatie", verbose_name="Combinatie")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="combinatie_items", to="pricelist.product", verbose_name="Product")),
                ("geselecteerde_opties", models.ManyToManyField(blank=True, help_text="Opties bij dit product die in de combinatie zijn meegenomen (moeten opties van dit product zijn).", related_name="combinatie_item_opties", to="pricelist.product", verbose_name="Geselecteerde opties")),
            ],
            options={
                "verbose_name": "Combinatie-item",
                "verbose_name_plural": "Combinatie-items",
                "ordering": ("volgorde", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductOptie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("korte_omschrijving", models.CharField(blank=True, help_text="Korte weergavenaam voor deze optie (bijv. 'Display', 'Cutter'). Leeg = merk + type van het optie-product.", max_length=128, verbose_name="Korte omschrijving")),
                ("volgorde", models.PositiveIntegerField(default=0, verbose_name="Volgorde")),
                ("hoofdproduct", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="optie_regels", to="pricelist.product", verbose_name="Hoofdproduct")),
                ("optie_product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="als_optie_bij", to="pricelist.product", verbose_name="Optie (product)")),
            ],
            options={
                "verbose_name": "Productoptie",
                "verbose_name_plural": "Productopties",
                "ordering": ("volgorde", "optie_product__merk", "optie_product__type"),
                "unique_together": {("hoofdproduct", "optie_product")},
            },
        ),
        migrations.AlterField(
            model_name="combinatie",
            name="producten",
            field=models.ManyToManyField(blank=True, help_text="Verouderd: gebruik 'Combinatie-items' hieronder. Wordt nog gebruikt tot migratie.", related_name="combinaties", to="pricelist.product"),
        ),
        migrations.RunPython(copy_optie_voor_to_productoptie, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="optie_voor",
        ),
        migrations.RunPython(copy_combinatie_producten_to_items, migrations.RunPython.noop),
    ]
