# Generated by Django 6.0.3 on 2026-03-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0023_productoptie_combinatieitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vaste_verkoopprijs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Voor diensten (bijv. configuratie): vaste fee. Wordt als verkoopprijs gebruikt; voor marge telt inkoop als 0.', max_digits=10, null=True, verbose_name='Vaste verkoopprijs (dienst)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inkoopprijs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Niet nodig voor diensten met vaste fee (zie Vaste verkoopprijs).', max_digits=10, null=True),
        ),
    ]
