# Generated by Django 6.0.3 on 2026-03-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0024_product_vaste_verkoopprijs_inkoop_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marge_product',
            field=models.BooleanField(default=True, help_text="Staat standaard aan. Uitvinken voor diensten/overige posten: omzet telt mee in totaal maar niet in de margeberekening; toont als 'overige omzet'.", verbose_name='Marge product'),
        ),
        migrations.AlterField(
            model_name='combinatie',
            name='aanbieding_type',
            field=models.CharField(choices=[('geen', 'Geen aanbieding (set tegen reguliere prijzen)'), ('vast_bedrag', 'Vast bedrag (aanbiedingsprijs)'), ('korting_bedrag', 'Vast kortingsbedrag'), ('korting_percentage', 'Kortingspercentage')], default='vast_bedrag', help_text='Hoe de prijs van de combinatie wordt bepaald.', max_length=32),
        ),
    ]
