# Generated by Django 6.0.3 on 2026-03-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0025_product_marge_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='toon_prijsverloop_grafiek_productpagina',
            field=models.BooleanField(default=False, help_text='Toon op de productinformatiepagina een grafiek met het prijsverloop (inkoopprijs door de tijd).', verbose_name='Toon prijsverloop-grafiek op productpagina'),
        ),
        migrations.AlterField(
            model_name='combinatie',
            name='aanbieding_korting_bedrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vast kortingsbedrag op het totaal van de marge-producten (niet op overige omzet).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='combinatie',
            name='aanbieding_korting_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kortingspercentage op het totaal van de marge-producten (niet op overige omzet). Bijv. 10 = 10%.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='combinatie',
            name='aanbieding_type',
            field=models.CharField(choices=[('geen', 'Geen aanbieding (set tegen reguliere prijzen)'), ('vast_bedrag', 'Vast bedrag (aanbiedingsprijs)'), ('korting_bedrag', 'Kortingsbedrag'), ('korting_percentage', 'Kortingspercentage')], default='korting_bedrag', help_text='Hoe de prijs van de combinatie wordt bepaald.', max_length=32),
        ),
        migrations.AlterField(
            model_name='combinatie',
            name='aanbieding_vast_bedrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prijs voor het marge-producten deel. Overige omzet (diensten e.d.) wordt hierbij opgeteld.', max_digits=10, null=True),
        ),
    ]
