# Generated by Django 6.0.3 on 2026-03-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0026_toon_prijsverloop_grafiek'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='toon_prijsverloop_inkoop_productpagina',
            field=models.BooleanField(default=True, help_text='Toon de inkoopprijs in de prijsverloop-grafiek op de productpagina.', verbose_name='Inkoopprijs in prijsverloop-grafiek'),
        ),
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='toon_prijsverloop_verkoop_productpagina',
            field=models.BooleanField(default=False, help_text='Toon de verkoopprijs (berekend uit inkoop + winstprofiel) in de prijsverloop-grafiek.', verbose_name='Verkoopprijs in prijsverloop-grafiek'),
        ),
        migrations.AlterField(
            model_name='algemeneinstellingen',
            name='toon_prijsverloop_grafiek_productpagina',
            field=models.BooleanField(default=False, help_text='Toon op de productinformatiepagina een grafiek met het prijsverloop.', verbose_name='Toon prijsverloop-grafiek op productpagina'),
        ),
    ]
