# Generated by Django 6.0.3 on 2026-03-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0027_toon_prijsverloop_inkoop_verkoop'),
    ]

    operations = [
        migrations.AddField(
            model_name='prijshistorie',
            name='verkoopprijs_op_datum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Verkoopprijs zoals die gold op de wijzigingsdatum (met toen geldend winstprofiel).', max_digits=10, null=True, verbose_name='Verkoopprijs op datum'),
        ),
    ]
