# Generated by Django 6.0.3 on 2026-03-14 03:35

import uuid
from collections import defaultdict

from django.db import migrations, models


def ensure_unique_artikelnummers(apps, schema_editor):
    """Geef producten met hetzelfde artikelnummer een nieuw uniek UUID (behoud eerste per groep)."""
    Product = apps.get_model("pricelist", "Product")
    by_artikelnummer = defaultdict(list)
    for p in Product.objects.all().order_by("pk"):
        by_artikelnummer[p.artikelnummer].append(p)
    for artikelnummer, products in by_artikelnummer.items():
        for p in products[1:]:  # behoud eerste, wijzig de rest
            p.artikelnummer = uuid.uuid4()
            p.save(update_fields=["artikelnummer"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0028_prijshistorie_verkoopprijs_op_datum'),
    ]

    operations = [
        migrations.RunPython(ensure_unique_artikelnummers, noop),
        migrations.AlterField(
            model_name='product',
            name='artikelnummer',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Technisch artikelnummer (UUID) voor bestandsnamen en koppelingen. Uniek per product.', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bestelnummer_leverancier',
            field=models.CharField(blank=True, help_text='Bestel-/artikelnummer zoals gehanteerd door de leverancier. Hetzelfde artikel (merk/type) mag meerdere keren voorkomen als bestelnummer of leverancier afwijkt.', max_length=255),
        ),
    ]
