# Generated by Django 6.0.3 on 2026-03-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0029_product_artikelnummer_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='toon_categorie_frontend',
            field=models.BooleanField(default=True, help_text='Toon de categorie op de prijslijst en productpagina.', verbose_name='Toon categorie op frontend'),
        ),
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='toon_leverancier_frontend',
            field=models.BooleanField(default=True, help_text='Toon de leverancier op de prijslijst en productpagina.', verbose_name='Toon leverancier op frontend'),
        ),
    ]
