# Generated by Django 6.0.3 on 2026-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0030_toon_leverancier_categorie_frontend'),
    ]

    operations = [
        migrations.AddField(
            model_name='algemeneinstellingen',
            name='taal',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Nederlands')], default='en', help_text='Taal voor de prijslijst en productpagina. Admin blijft in de browser-/systeemtaal.', max_length=5, verbose_name='Taal (frontend)'),
        ),
    ]
