# Generated by Django 6.0.3 on 2026-03-14 16:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0039_combination_image_usps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCalculationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.03'), help_text='E.g. 0.03 for 3% of total hardware value.', max_digits=6, verbose_name='Hardware fee percentage')),
                ('visits_3_years', models.PositiveIntegerField(default=12, help_text='Number of visits over the 3-year contract period.', verbose_name='Visits (3 years)')),
                ('visits_5_years', models.PositiveIntegerField(default=20, help_text='Number of visits over the 5-year contract period.', verbose_name='Visits (5 years)')),
                ('minutes_per_item', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Time per product in minutes.', max_digits=6, verbose_name='Minutes per item')),
                ('minimum_minutes_per_visit', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Minimum visit duration in minutes.', max_digits=6, verbose_name='Minimum minutes per visit')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('65.00'), help_text='Mechanic hourly rate in euros.', max_digits=8, verbose_name='Hourly rate (€)')),
            ],
            options={
                'verbose_name': 'Contract calculation settings',
                'verbose_name_plural': 'Contract calculation settings',
                'db_table': 'catalogus_contractcalculationsettings',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='combination',
            options={'verbose_name': 'Combination', 'verbose_name_plural': 'Combinations'},
        ),
        migrations.AlterModelOptions(
            name='combinationitem',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Combination item', 'verbose_name_plural': 'Combination items'},
        ),
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'General setting', 'verbose_name_plural': 'General settings'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'Price history', 'verbose_name_plural': 'Price histories'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ('sort_order', 'option_product__brand', 'option_product__model_type'), 'verbose_name': 'Product option', 'verbose_name_plural': 'Product options'},
        ),
        migrations.AlterModelOptions(
            name='profitprofile',
            options={'ordering': ('name',), 'verbose_name': 'Profit profile', 'verbose_name_plural': 'Profit profiles'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Optional: use this to sort categories.'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='combination_sales_price',
            field=models.DecimalField(decimal_places=2, help_text='Legacy field: final offer price. Filled automatically from type and discount fields.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='combination',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount on the total of margin products (not on other revenue).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='combination',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage on the total of margin products (not on other revenue). E.g. 10 = 10%.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='combination',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='combination',
            name='offer_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the margin-products part. Other revenue (services etc.) is added to this.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='combination',
            name='offer_type',
            field=models.CharField(choices=[('none', 'No offer (set at regular prices)'), ('fixed_amount', 'Fixed amount (offer price)'), ('discount_amount', 'Discount amount'), ('discount_percentage', 'Discount percentage')], default='discount_amount', help_text='How the combination price is determined.', max_length=32),
        ),
        migrations.AlterField(
            model_name='combination',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Deprecated: use Combination items below. Still used until migration.', related_name='combinations', to='pricelist.product'),
        ),
        migrations.AlterField(
            model_name='combinationitem',
            name='combination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricelist.combination', verbose_name='Combination'),
        ),
        migrations.AlterField(
            model_name='combinationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combination_items', to='pricelist.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='combinationitem',
            name='selected_options',
            field=models.ManyToManyField(blank=True, help_text='Options for this product included in the combination (must be options of this product).', related_name='combination_item_options', to='pricelist.product', verbose_name='Selected options'),
        ),
        migrations.AlterField(
            model_name='combinationitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='currency',
            field=models.CharField(default='EUR', help_text='Currency code or symbol for display, e.g. EUR or €.', max_length=32, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], default='en', help_text='Language for the price list and product page. Admin keeps browser/system language.', max_length=5, verbose_name='Language (frontend)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='minimum_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum margin % for combinations (e.g. 20 = at least 20% margin). At 0 no check is performed.', max_digits=5, verbose_name='Minimum margin %'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='number_format',
            field=models.CharField(choices=[('eu', 'Europe (period for thousands, comma for decimals: 1.000,00)'), ('us', 'US (comma for thousands, period for decimals: 1,000.00)')], default='eu', help_text='Separators: Europe = 1.000,00 ; US = 1,000.00', max_length=8, verbose_name='Number format'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='rounding',
            field=models.CharField(default='0.01', help_text='Rounding syntax: number = round to that amount (0.01, 0.05, 0.10, 0.50, 1, 5, 10, …). Option: number-minus (e.g. 1-0.01) = round to whole units then subtract.', max_length=64, verbose_name='Rounding'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='show_category_on_frontend',
            field=models.BooleanField(default=True, help_text='Show the category on the price list and product page.', verbose_name='Show category on frontend'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='show_cost_in_price_history_chart',
            field=models.BooleanField(default=True, help_text='Show cost price in the price history chart on the product page.', verbose_name='Cost price in price history chart'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='show_price_history_chart_on_product_page',
            field=models.BooleanField(default=False, help_text='Show a price history chart on the product page.', verbose_name='Show price history chart on product page'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='show_sales_in_price_history_chart',
            field=models.BooleanField(default=False, help_text='Show sales price (from cost + profit profile) in the price history chart.', verbose_name='Sales price in price history chart'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='show_supplier_on_frontend',
            field=models.BooleanField(default=True, help_text='Show the supplier on the price list and product page.', verbose_name='Show supplier on frontend'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='change_date',
            field=models.DateField(verbose_name='Change date'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='new_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New cost price'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='previous_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Previous cost price'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='pricelist.product'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='sales_price_at_date',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sales price as it was on the change date (with the profit profile then in effect).', max_digits=10, null=True, verbose_name='Sales price at date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Technical article number (UUID) for filenames and links. Unique per product.', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='E.g. HP, Epson.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pricelist.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Not required for services with fixed fee (see Fixed sales price).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fixed_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For services (e.g. configuration): fixed fee. Used as sales price; for margin, cost counts as 0.', max_digits=10, null=True, verbose_name='Fixed sales price (service)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_margin_product',
            field=models.BooleanField(default=True, help_text="On by default. Turn off for services/other items: revenue counts in total but not in margin calculation; shown as 'other revenue'.", verbose_name='Margin product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_type',
            field=models.CharField(blank=True, help_text='E.g. model name or type.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Deprecated; use brand + model_type instead.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_last_checked',
            field=models.DateField(blank=True, help_text='Date when the price was last checked.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit_profile',
            field=models.ForeignKey(blank=True, help_text='Required profit profile for this product (in admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pricelist.profitprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_in_price_list',
            field=models.BooleanField(default=True, help_text='If disabled: this product does not appear as a standalone item on the price list. It remains visible as an option on other products.', verbose_name='Show in price list'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricelist.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier_order_number',
            field=models.CharField(blank=True, help_text='Order/article number used by the supplier. Same article (brand/type) may appear multiple times if order number or supplier differs.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='usps',
            field=models.TextField(blank=True, help_text='USPs, one per line'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_lines', to='pricelist.product', verbose_name='Main product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_option_for', to='pricelist.product', verbose_name='Option (product)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='short_description',
            field=models.CharField(blank=True, help_text="Short display name for this option (e.g. 'Display', 'Cutter'). Empty = brand + type of option product.", max_length=128, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='profitprofile',
            name='markup_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed markup in euros added to the sales price.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='profitprofile',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Percentage markup on cost price (e.g. 30 for 30%).', max_digits=5),
        ),
        migrations.AlterModelTable(
            name='category',
            table='catalogus_category',
        ),
        migrations.AlterModelTable(
            name='combination',
            table='catalogus_combinatie',
        ),
        migrations.AlterModelTable(
            name='combinationitem',
            table='catalogus_combinatieitem',
        ),
        migrations.AlterModelTable(
            name='generalsettings',
            table='catalogus_generalsettings',
        ),
        migrations.AlterModelTable(
            name='pricehistory',
            table='catalogus_pricehistory',
        ),
        migrations.AlterModelTable(
            name='productoption',
            table='catalogus_productoption',
        ),
        migrations.AlterModelTable(
            name='profitprofile',
            table='catalogus_profitprofile',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='catalogus_supplier',
        ),
    ]
