# Generated by Django 6.0.3 on 2026-03-14 19:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0040_contract_calculation_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g. '3 years' or '5 years'.", max_length=64, verbose_name='Name')),
                ('duration_months', models.PositiveIntegerField(help_text='Contract length in months, e.g. 36 or 60.', verbose_name='Duration (months)')),
                ('hardware_fee_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total hardware value as fee, e.g. 10 or 7.5.', max_digits=5, verbose_name='Hardware fee (%)')),
                ('is_active', models.BooleanField(default=True, help_text='If unchecked, this option will not appear on the proposal.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Contract duration',
                'verbose_name_plural': 'Contract durations',
                'db_table': 'catalogus_contractduration',
                'ordering': ('duration_months',),
            },
        ),
        migrations.DeleteModel(
            name='ContractCalculationSettings',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Hourly rate for labour cost calculation.', max_digits=10, verbose_name='Technician hourly rate'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='minimum_visit_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Minimum duration of a maintenance visit (used if calculated time is lower).', max_digits=6, verbose_name='Minimum visit time (minutes)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='time_per_product_minutes',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Estimated minutes per product per maintenance visit.', max_digits=6, verbose_name='Time per product (minutes)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='visits_per_year',
            field=models.PositiveIntegerField(default=2, help_text='Number of maintenance visits per year in the contract.', verbose_name='Visits per year'),
        ),
    ]
