# Generated by Django 6.0.3 on 2026-03-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0041_contract_duration_and_maintenance_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='visits_per_year',
        ),
        migrations.AddField(
            model_name='contractduration',
            name='visits_per_year',
            field=models.PositiveIntegerField(default=2, help_text='Number of maintenance visits per year for this contract.', verbose_name='Visits per year'),
        ),
    ]
