# Generated by Django 6.0.3 on 2026-03-14 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0042_contract_duration_visits_per_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractduration',
            name='visits_per_year',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Number of maintenance visits per year for this contract (e.g. 2 or 2.5).', max_digits=5, verbose_name='Visits per year'),
        ),
    ]
