# Generated by Django 6.0.3 on 2026-03-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0043_contract_duration_visits_per_year_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='show_contract_fee_calculation',
            field=models.BooleanField(default=False, help_text='When enabled, the proposal page shows the calculation breakdown (hardware fee, labour, etc.) below each contract option.', verbose_name='Show fee calculation on proposal'),
        ),
    ]
