# Generated by Django 6.0.3 on 2026-03-14 21:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0045_visits_per_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Optional reference or name for this calculation.', max_length=255, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Saved proposal',
                'verbose_name_plural': 'Saved proposals',
                'db_table': 'catalogus_proposal',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='At')),
                ('action', models.CharField(choices=[('created', 'Created'), ('saved', 'Saved'), ('updated_rates', 'Prices updated to current'), ('line_added', 'Line added'), ('line_removed', 'Line removed'), ('quantity_changed', 'Quantity changed'), ('reference_changed', 'Reference changed'), ('edited', 'Edited')], max_length=32, verbose_name='Action')),
                ('description', models.TextField(blank=True, help_text='Optional human-readable description.', verbose_name='Description')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Optional structured data (e.g. line id, old/new values).', verbose_name='Details')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='pricelist.proposal', verbose_name='Proposal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Proposal history entry',
                'verbose_name_plural': 'Proposal history entries',
                'db_table': 'catalogus_proposalhistory',
                'ordering': ('-at',),
            },
        ),
        migrations.CreateModel(
            name='ProposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('line_type', models.CharField(choices=[('product', 'Product'), ('combination', 'Combination')], max_length=16, verbose_name='Type')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='Quantity')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit price (at save)')),
                ('line_total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line total (at save)')),
                ('name_snapshot', models.CharField(blank=True, help_text='Stored name for display when product/combination is later removed.', max_length=255, verbose_name='Name (at save)')),
                ('is_removed', models.BooleanField(default=False, help_text="True after 'update to current rates' when this product/combination no longer exists.", verbose_name='No longer in catalog')),
                ('combination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_lines', to='pricelist.combination', verbose_name='Combination')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_lines', to='pricelist.product', verbose_name='Product')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricelist.proposal', verbose_name='Proposal')),
            ],
            options={
                'verbose_name': 'Proposal line',
                'verbose_name_plural': 'Proposal lines',
                'db_table': 'catalogus_proposalline',
                'ordering': ('proposal', 'sort_order', 'id'),
            },
        ),
    ]
