# Generated by Django 6.0.3 on 2026-03-15 06:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0046_saved_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='hourly_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly rate at save'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='minimum_visit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Minimum visit time (minutes) at save'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='time_per_product_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Time per product (minutes) at save'),
        ),
        migrations.CreateModel(
            name='ProposalContractSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Duration (months)')),
                ('hardware_fee_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hardware fee (%)')),
                ('visits_per_contract', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=6, verbose_name='Visits per contract period')),
                ('contract_duration', models.ForeignKey(blank=True, help_text="Link to current contract duration; null if it was deleted. Used to detect 'removed'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_contract_snapshots', to='pricelist.contractduration', verbose_name='Contract duration (reference)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_snapshots', to='pricelist.proposal', verbose_name='Proposal')),
            ],
            options={
                'verbose_name': 'Proposal contract snapshot',
                'verbose_name_plural': 'Proposal contract snapshots',
                'db_table': 'catalogus_proposalcontractsnapshot',
                'ordering': ('proposal', 'sort_order', 'id'),
            },
        ),
    ]
