# Generated by Django 6.0.3 on 2026-03-16 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0050_uuid_supplier_category_profitprofile_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalLineOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_selected_option_in_proposals', to='pricelist.product', verbose_name='Option (product)')),
                ('proposal_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='pricelist.proposalline', verbose_name='Proposal line')),
            ],
            options={
                'verbose_name': 'Proposal line option',
                'verbose_name_plural': 'Proposal line options',
                'db_table': 'catalogus_proposallineoption',
                'ordering': ('proposal_line', 'id'),
                'unique_together': {('proposal_line', 'option_product')},
            },
        ),
    ]
