# Generated by Django 6.0.3 on 2026-03-16 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0051_proposal_line_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, help_text='Optional order reference (defaults to proposal reference).', max_length=255, verbose_name='Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='pricelist.proposal', verbose_name='Proposal')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'catalogus_order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(blank=True, help_text='When this line was ordered at the supplier.', null=True, verbose_name='Ordered at')),
                ('expected_delivery', models.DateField(blank=True, help_text='Expected delivery date.', null=True, verbose_name='Expected delivery')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When this line was delivered.', null=True, verbose_name='Delivered at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricelist.order', verbose_name='Order')),
                ('proposal_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_line', to='pricelist.proposalline', verbose_name='Proposal line')),
            ],
            options={
                'verbose_name': 'Order line',
                'verbose_name_plural': 'Order lines',
                'db_table': 'catalogus_orderline',
                'ordering': ('order', 'proposal_line__sort_order', 'id'),
            },
        ),
    ]
