# Generated by Django 6.0.3 on 2026-03-16 19:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_order_line_items(apps, schema_editor):
    """
    Create one OrderLineItem per OrderLine for existing orders. For product lines: one item with
    combination_item=None. For combination lines: one item per CombinationItem. Copies
    ordered_at/expected_delivery/delivered_at from OrderLine so existing data is preserved.
    """
    OrderLine = apps.get_model("pricelist", "OrderLine")
    OrderLineItem = apps.get_model("pricelist", "OrderLineItem")
    CombinationItem = apps.get_model("pricelist", "CombinationItem")
    for ol in OrderLine.objects.select_related("proposal_line"):
        if ol.items.exists():
            continue
        pl = ol.proposal_line
        if pl.line_type == "combination" and pl.combination_id:
            for item in CombinationItem.objects.filter(combination_id=pl.combination_id).order_by("sort_order", "id"):
                OrderLineItem.objects.create(
                    order_line=ol,
                    combination_item=item,
                    ordered_at=ol.ordered_at,
                    expected_delivery=ol.expected_delivery,
                    delivered_at=ol.delivered_at,
                )
        else:
            OrderLineItem.objects.create(
                order_line=ol,
                combination_item=None,
                ordered_at=ol.ordered_at,
                expected_delivery=ol.expected_delivery,
                delivered_at=ol.delivered_at,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0052_order_and_orderline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(blank=True, help_text='When this item was ordered at the supplier.', null=True, verbose_name='Ordered at')),
                ('expected_delivery', models.DateField(blank=True, help_text='Expected delivery date.', null=True, verbose_name='Expected delivery')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When this item was delivered.', null=True, verbose_name='Delivered at')),
                ('combination_item', models.ForeignKey(blank=True, help_text='Set for items inside a combination; empty for a single product line.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_line_items', to='pricelist.combinationitem', verbose_name='Combination item')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricelist.orderline', verbose_name='Order line')),
            ],
            options={
                'verbose_name': 'Order line item',
                'verbose_name_plural': 'Order line items',
                'db_table': 'catalogus_orderlineitem',
                'ordering': ('order_line', 'combination_item__sort_order', 'id'),
            },
        ),
        migrations.RunPython(backfill_order_line_items, noop_reverse),
    ]
