# Generated by Django 6.0.3 on 2026-03-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0053_add_order_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note for this order.', verbose_name='Order note'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Draft: not yet sent. Sent: with supplier(s). Completed: all delivered. Cancelled.', max_length=32, verbose_name='Status'),
        ),
    ]
