# Generated by Django 6.0.3 on 2026-03-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0054_order_status_and_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo shown in the header of the frontend and in the admin. Recommended: SVG or PNG, reasonable height (e.g. 48px).', null=True, upload_to='general', verbose_name='Logo'),
        ),
    ]
