# Generated by Django 6.0.3 on 2026-03-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0055_general_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='primary_color',
            field=models.CharField(default='#e01581', help_text='Hex colour for buttons, links and accents (e.g. #e01581 for PMS 226c). Used on frontend and in admin.', max_length=9, verbose_name='Primary colour (brand)'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='primary_color_hover',
            field=models.CharField(blank=True, help_text='Optional. Darker hex for hover states. Leave empty to use an automatic darker variant of the primary colour.', max_length=9, verbose_name='Primary colour hover'),
        ),
    ]
