# Generated by Django 6.0.3 on 2026-03-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0057_ensure_primary_color_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='site_name',
            field=models.CharField(blank=True, default='NovaQuote', help_text='Title and brand name shown on the frontend (e.g. in the header and page titles).', max_length=255, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo shown in the header of the frontend. Recommended: SVG or PNG, reasonable height (e.g. 48px).', null=True, upload_to='general', verbose_name='Logo'),
        ),
    ]
