# Generated by Django 6.0.3 on 2026-03-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0059_ensure_proposallineoption_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='catalogus_product',
        ),
    ]
