# Generated by Django 6.0.3 on 2026-03-20 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0061_add_uuid_identifiers_core_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and UI anchors.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and UI anchors.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and integrations.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='proposalcontractsnapshot',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and integrations.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and stable UI anchors.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='proposallineoption',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and integrations.', unique=True, verbose_name='UUID'),
        ),
    ]
