# Generated by Django 6.0.3 on 2026-03-20 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0063_add_uuid_identifiers_remaining_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and integrations.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for the settings record (mostly for integrations/tests).', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and audit views.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references and integrations.', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='proposalhistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for external references.', unique=True, verbose_name='UUID'),
        ),
    ]
