# Generated by Django 6.0.3 on 2026-03-20 19:23

import django.db.models.deletion
import pricelist.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0064_alter_uuid_field_verbose_help_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for URLs and integrations.', unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Company name')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Legal name')),
                ('vat_number', models.CharField(blank=True, max_length=64, verbose_name='VAT number')),
                ('coc_number', models.CharField(blank=True, help_text='KvK / trade register number.', max_length=64, verbose_name='Chamber of Commerce number')),
                ('billing_line1', models.CharField(blank=True, max_length=255, verbose_name='Billing address line 1')),
                ('billing_line2', models.CharField(blank=True, max_length=255, verbose_name='Billing address line 2')),
                ('billing_city', models.CharField(blank=True, max_length=128, verbose_name='Billing city')),
                ('billing_postal_code', models.CharField(blank=True, max_length=32, verbose_name='Billing postal code')),
                ('billing_country', models.CharField(blank=True, max_length=128, verbose_name='Billing country')),
                ('shipping_line1', models.CharField(blank=True, max_length=255, verbose_name='Shipping address line 1')),
                ('shipping_line2', models.CharField(blank=True, max_length=255, verbose_name='Shipping address line 2')),
                ('shipping_city', models.CharField(blank=True, max_length=128, verbose_name='Shipping city')),
                ('shipping_postal_code', models.CharField(blank=True, max_length=32, verbose_name='Shipping postal code')),
                ('shipping_country', models.CharField(blank=True, max_length=128, verbose_name='Shipping country')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='General email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='General phone')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('iban', models.CharField(blank=True, max_length=64, verbose_name='IBAN')),
                ('bic_swift', models.CharField(blank=True, max_length=32, verbose_name='BIC / SWIFT')),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. Net 30', max_length=128, verbose_name='Payment terms')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Credit limit')),
                ('incoterms', models.CharField(blank=True, max_length=32, verbose_name='Incoterms')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead time (days)')),
                ('moq', models.CharField(blank=True, help_text='Minimum order quantity (text or number).', max_length=128, verbose_name='MOQ')),
                ('network_value_proposition', models.TextField(blank=True, help_text='Why this network partner is useful (when NETWORK role applies).', verbose_name='Value proposition')),
                ('network_industry_niche', models.CharField(blank=True, help_text='For network partners.', max_length=255, verbose_name='Industry / niche')),
                ('lead_pipeline_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], help_text='Used for leads in the pipeline; optional for other roles.', max_length=32, verbose_name='Lead pipeline status')),
                ('client_since', models.DateTimeField(blank=True, editable=False, help_text='Set when the organization first became a client (auto or manual).', null=True, verbose_name='Client since')),
                ('suppress_auto_client_promotion', models.BooleanField(default=False, help_text='If enabled, registering invoices/shipments will not promote LEAD → CLIENT.', verbose_name='Suppress automatic client promotion')),
                ('client_promotion_override', models.CharField(choices=[('auto', 'Automatic (first invoice/shipment promotes lead to client)'), ('manual_client', 'Manual: always treat as client (adds CLIENT role)'), ('manual_lead', 'Manual: keep as lead (no auto promotion from invoice/shipment)')], default='auto', max_length=32, verbose_name='Client promotion mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'catalogus_organization',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Personal email')),
                ('personal_mobile', models.CharField(blank=True, max_length=64, verbose_name='Personal mobile')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('spouse_partner_name', models.CharField(blank=True, max_length=255, verbose_name='Spouse / partner name')),
                ('family_details', models.JSONField(blank=True, default=pricelist.models._empty_json_list, help_text='JSON list, e.g. [{"name": "Alex", "age": 12}].', verbose_name='Family details')),
                ('pets', models.JSONField(blank=True, default=pricelist.models._empty_json_list, help_text='JSON list, e.g. [{"name": "Rex", "species": "dog"}].', verbose_name='Pets')),
                ('hobbies_interests', models.JSONField(blank=True, default=pricelist.models._empty_json_list, help_text='JSON list of strings.', verbose_name='Hobbies & interests')),
                ('communication_preferences', models.TextField(blank=True, help_text='How and when they prefer to be contacted.', verbose_name='Communication preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'catalogus_person',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Department name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='General email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='General phone')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='pricelist.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'catalogus_department',
                'ordering': ('organization', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('invoice_number', models.CharField(max_length=128, verbose_name='Invoice number')),
                ('issued_on', models.DateField(verbose_name='Issue date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pricelist.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization invoice',
                'verbose_name_plural': 'Organization invoices',
                'db_table': 'catalogus_organizationinvoice',
                'ordering': ('-issued_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('reference', models.CharField(max_length=128, verbose_name='Shipment reference')),
                ('shipped_on', models.DateField(verbose_name='Ship date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='pricelist.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization shipment',
                'verbose_name_plural': 'Organization shipments',
                'db_table': 'catalogus_organizationshipment',
                'ordering': ('-shipped_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Job title')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Company email')),
                ('company_phone', models.CharField(blank=True, max_length=64, verbose_name='Company phone')),
                ('phone_extension', models.CharField(blank=True, max_length=32, verbose_name='Extension')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='Primary contact')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='pricelist.department', verbose_name='Department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pricelist.organization', verbose_name='Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pricelist.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Organization membership',
                'verbose_name_plural': 'Organization memberships',
                'db_table': 'catalogus_organizationperson',
                'ordering': ('organization', 'person'),
            },
        ),
        migrations.CreateModel(
            name='PersonLifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('occurred_on', models.DateField(verbose_name='Date')),
                ('note', models.TextField(verbose_name='Note')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_events', to='pricelist.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Person life event',
                'verbose_name_plural': 'Person life events',
                'db_table': 'catalogus_personlifeevent',
                'ordering': ('-occurred_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('role', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CLIENT', 'Client'), ('LEAD', 'Lead'), ('NETWORK', 'Network')], max_length=32, verbose_name='Role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='pricelist.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization role',
                'verbose_name_plural': 'Organization roles',
                'db_table': 'catalogus_organizationrole',
                'constraints': [models.UniqueConstraint(fields=('organization', 'role'), name='uniq_organization_role')],
            },
        ),
    ]
