# Generated by Django 6.0.3 on 2026-03-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0065_contacts_crm_models'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('vat_number', ''), _negated=True), fields=('vat_number',), name='uniq_catalogus_organization_vat_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('coc_number', ''), _negated=True), fields=('coc_number',), name='uniq_catalogus_organization_coc_nonempty'),
        ),
    ]
