# Generated by Django 6.0.3 on 2026-03-20 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0066_organization_vat_coc_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('linked_organization', models.ForeignKey(help_text='Supplier, client, or lead organization this relationship is recorded on.', on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_network_links', to='pricelist.organization', verbose_name='Linked company')),
                ('network_organization', models.ForeignKey(help_text='Organization with the network/partner role.', on_delete=django.db.models.deletion.CASCADE, related_name='network_partner_links', to='pricelist.organization', verbose_name='Network partner')),
            ],
            options={
                'verbose_name': 'Network link',
                'verbose_name_plural': 'Network links',
                'db_table': 'catalogus_organizationnetworklink',
                'ordering': ('network_organization', 'linked_organization'),
                'constraints': [models.UniqueConstraint(fields=('network_organization', 'linked_organization'), name='uniq_organization_network_link_pair')],
            },
        ),
    ]
