# Generated by Django 6.0.3 on 2026-03-20 20:13

import json
import uuid

import django.db.models.deletion
from django.db import migrations, models


def migrate_hobbies_interests_to_rows(apps, schema_editor):
    Person = apps.get_model("pricelist", "Person")
    PersonHobby = apps.get_model("pricelist", "PersonHobby")
    for p in Person.objects.all():
        raw = p.hobbies_interests
        if raw in (None, "", []):
            continue
        items = raw
        if isinstance(items, str):
            try:
                items = json.loads(items)
            except (json.JSONDecodeError, TypeError, ValueError):
                continue
        if not isinstance(items, list):
            continue
        for i, item in enumerate(items):
            if isinstance(item, str) and item.strip():
                PersonHobby.objects.create(
                    person_id=p.pk,
                    name=item.strip()[:255],
                    sort_order=i,
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("pricelist", "0067_organization_network_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=255, verbose_name="Event name")),
                ("event_date", models.DateField(verbose_name="Date")),
                (
                    "reminder",
                    models.CharField(
                        choices=[
                            ("none", "No reminder"),
                            ("on_day", "On the day"),
                            ("1_day_before", "One day before"),
                            ("1_week_before", "One week before"),
                            ("2_weeks_before", "Two weeks before"),
                            ("1_month_before", "One month before"),
                        ],
                        default="none",
                        help_text="When you want to be reminded relative to the event date.",
                        max_length=32,
                        verbose_name="Reminder",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_events",
                        to="pricelist.person",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "catalogus_personevent",
                "ordering": ("event_date", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="PersonHobby",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=255, verbose_name="Hobby or interest")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Sort order")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hobbies",
                        to="pricelist.person",
                        verbose_name="Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hobby or interest",
                "verbose_name_plural": "Hobbies & interests",
                "db_table": "catalogus_personhobby",
                "ordering": ("sort_order", "name", "id"),
            },
        ),
        migrations.RunPython(migrate_hobbies_interests_to_rows, noop_reverse),
        migrations.RemoveField(
            model_name="person",
            name="family_details",
        ),
        migrations.RemoveField(
            model_name="person",
            name="hobbies_interests",
        ),
        migrations.RemoveField(
            model_name="person",
            name="pets",
        ),
    ]
