# Generated by Django 6.0.3 on 2026-03-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0068_person_hobbies_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='spouse_partner_name',
        ),
    ]
