# Generated by Django 6.0.3 on 2026-03-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0069_remove_person_spouse_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_crm_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_supplier_crm', to='pricelist.organizationperson', verbose_name='Supplier contact person'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_crm_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_supplier_crm', to='pricelist.department', verbose_name='Supplier department'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_crm_organization',
            field=models.ForeignKey(blank=True, help_text='CRM organization with the supplier role for this catalog supplier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_supplier_crm', to='pricelist.organization', verbose_name='Supplier company (Contacts)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_crm_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_client_crm', to='pricelist.organizationperson', verbose_name='Client contact person'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_crm_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_client_crm', to='pricelist.department', verbose_name='Client department'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_crm_organization',
            field=models.ForeignKey(blank=True, help_text='CRM organization with the client or lead role for this proposal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_client_crm', to='pricelist.organization', verbose_name='Client / lead company (Contacts)'),
        ),
    ]
