# Generated by Django 6.0.3 on 2026-03-20 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _backfill_product_suppliers(apps, schema_editor):
    Product = apps.get_model("pricelist", "Product")
    ProductSupplier = apps.get_model("pricelist", "ProductSupplier")
    for p in Product.objects.iterator(chunk_size=500):
        if not p.supplier_id:
            continue
        ProductSupplier.objects.get_or_create(
            product_id=p.pk,
            supplier_id=p.supplier_id,
            defaults={
                "cost_price": p.cost_price,
                "supplier_order_number": (p.supplier_order_number or "")[:255],
                "is_preferred": True,
                "sort_order": 0,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("pricelist", "0070_product_proposal_crm_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalline",
            name="supplier_name_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Frozen supplier label for display if the offer is later removed.",
                max_length=255,
                verbose_name="Supplier name (at save)",
            ),
        ),
        migrations.CreateModel(
            name="ProductSupplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Stable identifier for integrations and proposal line references.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase cost from this supplier (same rules as product cost: optional for fixed-fee services).",
                        max_digits=10,
                        null=True,
                        verbose_name="Cost price",
                    ),
                ),
                ("supplier_order_number", models.CharField(blank=True, max_length=255, verbose_name="Supplier order / article number")),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text='Typical delivery lead time for proposals sorted by "fastest".',
                        null=True,
                        verbose_name="Lead time (days)",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Net 30 — shown in proposal supplier picker.",
                        max_length=128,
                        verbose_name="Payment terms (label)",
                    ),
                ),
                (
                    "payment_terms_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Numeric days until due (e.g. 30). Used for “best payment terms” (longer is better cashflow).",
                        null=True,
                        verbose_name="Payment due (days)",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="Price list and default proposal line use this row when multiple suppliers exist.",
                        verbose_name="Preferred supplier",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_suppliers",
                        to="pricelist.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_supplier_offers",
                        to="pricelist.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product supplier offer",
                "verbose_name_plural": "Product supplier offers",
                "db_table": "catalogus_productsupplier",
                "ordering": ("product", "sort_order", "supplier__name"),
            },
        ),
        migrations.AddField(
            model_name="proposalline",
            name="product_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Catalog supplier row used for this product line when saved.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposal_lines",
                to="pricelist.productsupplier",
                verbose_name="Chosen supplier offer",
            ),
        ),
        migrations.AddConstraint(
            model_name="productsupplier",
            constraint=models.UniqueConstraint(fields=("product", "supplier"), name="uniq_product_supplier_offer"),
        ),
        migrations.RunPython(_backfill_product_suppliers, migrations.RunPython.noop),
    ]
