# Generated by Django 6.0.3

from django.db import migrations, models


def migrate_legacy_pink_to_teal(apps, schema_editor):
    GeneralSettings = apps.get_model("pricelist", "GeneralSettings")
    for row in GeneralSettings.objects.all():
        if (row.primary_color or "").lower() == "#e01581":
            row.primary_color = "#0d9488"
            row.save(update_fields=["primary_color"])


class Migration(migrations.Migration):

    dependencies = [
        ("pricelist", "0071_product_supplier_offers"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="color_scheme",
            field=models.CharField(
                choices=[
                    ("house_orange", "House of Orange (warm orange & red)"),
                    ("teal", "Teal (fresh, professional)"),
                    ("graytone", "Graytone (neutral slate)"),
                    ("high_contrast", "High contrast (accessibility)"),
                    ("spring", "Spring (greens & blossom)"),
                    ("summer", "Summer (coral & sky)"),
                    ("autumn", "Autumn (amber & rust)"),
                    ("winter", "Winter (frost & deep blue)"),
                    ("custom", "Custom (manual colours below)"),
                ],
                default="teal",
                help_text="Preset themes for buttons and links. Choose Custom to set hex colours yourself.",
                max_length=32,
                verbose_name="Color scheme",
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="primary_color",
            field=models.CharField(
                default="#0d9488",
                help_text='Used when Color scheme is “Custom”. Hex for buttons, links and accents.',
                max_length=9,
                verbose_name="Primary colour (brand)",
            ),
        ),
        migrations.RunPython(migrate_legacy_pink_to_teal, migrations.RunPython.noop),
    ]
