# Generated by Django 6.0.3 on 2026-03-21 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0074_product_combination_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Typical delivery lead time for proposals sorted by “fastest”.', null=True, verbose_name='Lead time (days)'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identifier for URLs and external references.', unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='Draft: internal. Sent: issued to the customer (required before creating an order).', max_length=16, verbose_name='Status')),
                ('invoice_number', models.CharField(blank=True, help_text='Optional display number; can be assigned when the invoice is sent.', max_length=64, verbose_name='Invoice number')),
                ('grand_total_snapshot', models.DecimalField(decimal_places=2, help_text='Total amount from proposal lines at invoice creation.', max_digits=14, verbose_name='Grand total (snapshot)')),
                ('currency_code', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('issued_at', models.DateTimeField(blank=True, help_text='Set when the invoice is marked as sent.', null=True, verbose_name='Issued at')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='pricelist.proposal', verbose_name='Proposal')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'catalogus_invoice',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice issued before this order (proposal → invoice → order).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pricelist.invoice', verbose_name='Invoice'),
        ),
    ]
