# Generated by Django 6.0.3 on 2026-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelist', '0075_invoice_and_order_invoice_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional. Replaces the bundled NovaQuote logo in the frontend and admin header. Leave empty to use the default. Recommended: PNG or SVG, moderate height (e.g. 48px).', null=True, upload_to='general', verbose_name='Logo'),
        ),
    ]
